export interface BoqTemplateItem {
  category: string;
  seq: number;
  name: string;
  unit: string;
  quantity: number;
  unitPrice: number;
  notes: string | null;
}

export interface BoqTemplate {
  id: string;
  name: string;
  description: string;
  baseAreaSqm: number;
  items: BoqTemplateItem[];
}

/**
 * Reference BOQ digitized from a real single-story (คสล.) 52 sqm house build
 * (material + labor quotation, 11 work categories, 137 line items, verified
 * to sum to the source document's grand total of 695,185 baht). Quantities
 * scale linearly with target area when applied via BoqTemplatesService.apply —
 * an approximation real projects should still review, not a substitute for a
 * contractor quote.
 */
export const BOQ_TEMPLATES: BoqTemplate[] = [
  {
    id: 'single-story-52sqm',
    name: 'บ้านชั้นเดียว คสล. 52 ตร.ม. (มาตรฐานอ้างอิง)',
    description: 'ก่ออิฐฉาบปูน หลังคาซีแพคโมเนีย วัสดุเกรดกลาง-ดี (CPAC/SCG/TOA/COTTO/Hafele/YAZAKI) — ดัดแปลงจากใบประมาณราคาจริง',
    baseAreaSqm: 52,
    items: [
      { category: "หมวดงานโครงสร้าง (Structural Work)", seq: 1, name: "คอนกรีตผสมเสร็จ 240 Ksc (SCG/CPAC)", unit: "คิว", quantity: 12, unitPrice: 2100, notes: "สำหรับฐานราก คาน พื้นบ้าน" },
      { category: "หมวดงานโครงสร้าง (Structural Work)", seq: 2, name: "เหล็กข้ออ้อย SD40 Ø12 มม. (มอก.)", unit: "เส้น", quantity: 75, unitPrice: 200, notes: "ใช้คานคอดิน" },
      { category: "หมวดงานโครงสร้าง (Structural Work)", seq: 3, name: "เหล็กกลม SR24 Ø9 มม. (มอก.)", unit: "เส้น", quantity: 48, unitPrice: 110, notes: "ใช้ผูกเหล็กพื้น" },
      { category: "หมวดงานโครงสร้าง (Structural Work)", seq: 4, name: "เหล็กกลม SR24 Ø6 มม. (มอก.)", unit: "เส้น", quantity: 64, unitPrice: 55, notes: "เหล็กปลอก" },
      { category: "หมวดงานโครงสร้าง (Structural Work)", seq: 5, name: "ลวดผูกเหล็ก", unit: "มัด", quantity: 4, unitPrice: 70, notes: "สำหรับผูกเหล็ก" },
      { category: "หมวดงานโครงสร้าง (Structural Work)", seq: 6, name: "ทรายหยาบผสมปูน", unit: "คิว", quantity: 5, unitPrice: 500, notes: "สำหรับปรับพื้น" },
      { category: "หมวดงานโครงสร้าง (Structural Work)", seq: 7, name: "หินเบอร์ 3", unit: "คิว", quantity: 5, unitPrice: 550, notes: "ใช้รองพื้นฐานราก" },
      { category: "หมวดงานโครงสร้าง (Structural Work)", seq: 8, name: "ไม้แบบเหล็ก ฟุตติ้ง คาน เสา (เช่าใช้งาน)", unit: "ตร.ม.", quantity: 80, unitPrice: 90, notes: "สำหรับเสา/คาน" },
      { category: "หมวดงานโครงสร้าง (Structural Work)", seq: 9, name: "แผ่นพื้นคอนกรีตสำเร็จรูป CPAC", unit: "ตร.ม.", quantity: 51.7, unitPrice: 250, notes: "สำหรับปูพื้น คสล." },
      { category: "หมวดงานโครงสร้าง (Structural Work)", seq: 10, name: "WIRE MESH 4 mm. @ 0.20 #", unit: "ตร.ม.", quantity: 100, unitPrice: 30, notes: "สำหรับปูพื้น คสล." },
      { category: "หมวดงานโครงสร้าง (Structural Work)", seq: 11, name: "ค่าแรงงานทำโครงสร้างทั้งหมด", unit: "ตร.ม.", quantity: 52, unitPrice: 900, notes: "เทพื้น เสา คาน" },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 1, name: "เหล็กกล่อง 2\"x2\" หนา 2.3 มม. (มอก.)", unit: "เส้น (6 ม.)", quantity: 35, unitPrice: 400, notes: "ใช้เป็นโครงหลักหลังคา" },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 2, name: "เหล็กกล่อง 1.5\"x1.5\" หนา 2.3 มม. (มอก.)", unit: "เส้น (6 ม.)", quantity: 25, unitPrice: 350, notes: "ใช้เป็นแปรรองกระเบื้อง" },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 3, name: "เหล็กกล่อง 1.2\"x1.2\" หนา 1.6 มม.", unit: "เส้น (6 ม.)", quantity: 20, unitPrice: 300, notes: "ใช้เป็นเหล็กรับเชิงชาย" },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 4, name: "แผ่นเพลทเหล็ก 10x10 ซม. หนา 6 มม.", unit: "แผ่น", quantity: 11, unitPrice: 60, notes: "สำหรับเกล้าหัวเสา" },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 5, name: "ค่าตัด/เชื่อมเกล้าหัวเสา + เพลท", unit: "จุด", quantity: 11, unitPrice: 100, notes: "รวมแรงช่างเหล็ก" },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 6, name: "สีรองพื้นกันสนิม TOA Rust Tech ขนาด 5 แกลลอน สีเทา", unit: "แกลลอน", quantity: 1, unitPrice: 1200, notes: "ใช้ทาโครงเหล็กทั้งหมด" },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 7, name: "น้ำมันสน / แปรง / ลูกกลิ้ง", unit: "ชุด", quantity: 1, unitPrice: 400, notes: "อุปกรณ์ใช้ร่วมกัน" },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 8, name: "กระเบื้องซีแพคโมเนีย รุ่นร่อน ตราเพชร", unit: "แผ่น", quantity: 1280, unitPrice: 15.5, notes: "ครอบคลุมพื้นที่หลังคา 129 ตร.ม." },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 9, name: "กระเบื้องครอบสันโค้ง (อกไก่)", unit: "แผ่น", quantity: 20, unitPrice: 68, notes: null },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 10, name: "กระเบื้องครอบตะเฆ่สัน", unit: "แผ่น", quantity: 110, unitPrice: 68, notes: null },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 11, name: "กระเบื้องครอบปิดปลายตะเฆ่สัน", unit: "แผ่น", quantity: 5, unitPrice: 80, notes: null },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 12, name: "แผ่นกันนก (SCG)", unit: "แผ่น", quantity: 13, unitPrice: 150, notes: "ป้องกันนกใต้กระเบื้อง" },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 13, name: "แผ่นกาวดายเท็กซ์ (ระบบครอบแห้ง)", unit: "ม้วน", quantity: 5, unitPrice: 650, notes: "ป้องกันน้ำซึมรอยต่อครอบ" },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 14, name: "เทปกาวกันรอยต่อใต้กระเบื้อง", unit: "ม้วน", quantity: 3, unitPrice: 480, notes: "ใช้ตามแนวรอยต่อ" },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 15, name: "ฉนวนกันความร้อนใต้หลังคา SCG Stay Cool", unit: "ม้วน", quantity: 2, unitPrice: 2450, notes: null },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 16, name: "ไม้เชิงชาย SCG (ไฟเบอร์ซีเมนต์)", unit: "เมตร", quantity: 48, unitPrice: 145, notes: "รวมอุปกรณ์ยึด" },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 17, name: "น็อตยิงกระเบื้อง/ยิงเหล็ก (สแตนเลส)", unit: "ตัว", quantity: 600, unitPrice: 1.5, notes: null },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 18, name: "รางน้ำสแตนเลส 4\"", unit: "เมตร", quantity: 12, unitPrice: 300, notes: "รวมอุปกรณ์แขวน" },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 19, name: "ค่าติดตั้งระบบหลังคา + เชื่อมโครงเหล็ก", unit: "ตร.ม.", quantity: 129, unitPrice: 120, notes: "รวมแรง + เครื่องมือ" },
      { category: "หมวดงานหลังคา (Roof Work)", seq: 20, name: "ค่าแรงมุงกระเบื้องซีแพค", unit: "ตร.ม.", quantity: 129, unitPrice: 100, notes: "รวมแรงและอุปกรณ์ยึด" },
      { category: "หมวดงานก่ออิฐ ฉาบปูน (Wall Work)", seq: 1, name: "อิฐมอญแดง 3 รู (6x20x10 ซม.)", unit: "ก้อน", quantity: 9000, unitPrice: 3.2, notes: "ใช้ประมาณ 40 ก้อน/ตร.ม." },
      { category: "หมวดงานก่ออิฐ ฉาบปูน (Wall Work)", seq: 2, name: "ปูนก่ออิฐ ", unit: "ถุง (50 กก.)", quantity: 35, unitPrice: 143, notes: "ก่อผนังทั้งหมด" },
      { category: "หมวดงานก่ออิฐ ฉาบปูน (Wall Work)", seq: 3, name: "ปูนฉาบผนังสำเร็จรูป ", unit: "ถุง (50 กก.)", quantity: 110, unitPrice: 90, notes: "ใช้ฉาบ 2 ด้าน" },
      { category: "หมวดงานก่ออิฐ ฉาบปูน (Wall Work)", seq: 4, name: "ทรายละเอียด", unit: "คิว", quantity: 6, unitPrice: 500, notes: "ใช้ผสมปูนฉาบ/ก่อ" },
      { category: "หมวดงานก่ออิฐ ฉาบปูน (Wall Work)", seq: 5, name: "น้ำยาประสานคอนกรีต (TOA Bonding Agent)", unit: "แกลลอน", quantity: 1, unitPrice: 480, notes: "ใช้ผสมปูนฉาบ" },
      { category: "หมวดงานก่ออิฐ ฉาบปูน (Wall Work)", seq: 6, name: "เหล็กเส้นกลม Ø6 มม. (ปลอกเสาเอ็น/ทับหลัง)", unit: "เส้น", quantity: 30, unitPrice: 55, notes: null },
      { category: "หมวดงานก่ออิฐ ฉาบปูน (Wall Work)", seq: 7, name: "เหล็กข้ออ้อย Ø9 มม. (เสาเอ็น/ทับหลัง)", unit: "เส้น", quantity: 25, unitPrice: 115, notes: null },
      { category: "หมวดงานก่ออิฐ ฉาบปูน (Wall Work)", seq: 8, name: "ลวดผูกเหล็ก", unit: "มัด", quantity: 3, unitPrice: 220, notes: "ใช้ผูกเหล็กเสาเอ็น/คานทับหลัง" },
      { category: "หมวดงานก่ออิฐ ฉาบปูน (Wall Work)", seq: 9, name: "ตะแกรงกรงไก่ (Wire Mesh ½ นิ้ว)", unit: "ตร.ม.", quantity: 20, unitPrice: 85, notes: "ป้องกันรอยร้าว" },
      { category: "หมวดงานก่ออิฐ ฉาบปูน (Wall Work)", seq: 10, name: "ค่าแรงก่ออิฐ/ฉาบ/จับเซี้ยม", unit: "ตร.ม.", quantity: 140, unitPrice: 250, notes: "รวมค่าแรงทั้งหมด" },
      { category: "หมวดงานก่ออิฐ ฉาบปูน (Wall Work)", seq: 11, name: "ค่าแรงทำเสาเอ็น/ทับหลัง", unit: "จุด", quantity: 15, unitPrice: 50, notes: "ตามช่องหน้าต่าง/ประตู" },
      { category: "หมวดงานก่ออิฐ ฉาบปูน (Wall Work)", seq: 12, name: "ค่าแรงเขิบ (Crave) รอบบ้านกันชื้น 10ซม", unit: "เมตร", quantity: 30, unitPrice: 50, notes: null },
      { category: "หมวดงานวงกบ ประตู หน้าต่าง (Door & Window Work)", seq: 1, name: "วงกบประตู UPVC  ขนาด 0.80x2.00 ม. สีไม้มินิมอล", unit: "วง", quantity: 5, unitPrice: 1000, notes: "ใช้สำหรับห้องนอน 3 บาน + ห้องน้ำ 2 บาน" },
      { category: "หมวดงานวงกบ ประตู หน้าต่าง (Door & Window Work)", seq: 2, name: "วงกบประตู UPVC  ขนาด 0.70x2.00 ม. สีไม้มินิมอล", unit: "วง", quantity: 2, unitPrice: 1000, notes: "สำหรับประตูห้องน้ำ" },
      { category: "หมวดงานวงกบ ประตู หน้าต่าง (Door & Window Work)", seq: 3, name: "ประตู UPVC ลูกฟัก (SCG) 0.80x2.00 ม. สีไม้โอ๊ตมินิมอล", unit: "บาน", quantity: 3, unitPrice: 2290, notes: "สำหรับห้องนอน" },
      { category: "หมวดงานวงกบ ประตู หน้าต่าง (Door & Window Work)", seq: 4, name: "ประตู UPVC ลูกฟักกันน้ำ  0.70x2.00 ม. สีไม้มินิมอล", unit: "บาน", quantity: 2, unitPrice: 2290, notes: "สำหรับห้องน้ำ" },
      { category: "หมวดงานวงกบ ประตู หน้าต่าง (Door & Window Work)", seq: 5, name: "ประตู UPVC บานเปิดออกหลังบ้าน 0.80x2.00 ม. สีขาว", unit: "บาน", quantity: 1, unitPrice: 2290, notes: "ประตูหลังบ้าน" },
      { category: "หมวดงานวงกบ ประตู หน้าต่าง (Door & Window Work)", seq: 6, name: "ประตูอลูมิเนียมกระจกบานเลื่อน 2.00x2.10 ม. สีขาว", unit: "ชุด", quantity: 1, unitPrice: 8000, notes: "ประตูหน้าบ้านบานคู่" },
      { category: "หมวดงานวงกบ ประตู หน้าต่าง (Door & Window Work)", seq: 7, name: "หน้าต่างอลูมิเนียมกระจกบานเลื่อน 1.00x1.00 ม. สีขาว", unit: "ชุด", quantity: 3, unitPrice: 2500, notes: "สำหรับห้องนอน" },
      { category: "หมวดงานวงกบ ประตู หน้าต่าง (Door & Window Work)", seq: 8, name: "หน้าต่างอลูมิเนียมกระจกบานกระทุ้ง 0.60x0.40 ม. สีขาว", unit: "ชุด", quantity: 2, unitPrice: 2290, notes: "สำหรับห้องน้ำ" },
      { category: "หมวดงานวงกบ ประตู หน้าต่าง (Door & Window Work)", seq: 9, name: "หน้าต่างกระจกทรงกลม (มูจิมินิมอล) Ø 0.60 ม.", unit: "ชุด", quantity: 1, unitPrice: 2690, notes: "กระจกทรงกลมตกแต่ง" },
      { category: "หมวดงานวงกบ ประตู หน้าต่าง (Door & Window Work)", seq: 10, name: "ลูกบิดประตู Hafele รุ่น Knob Set SS", unit: "ชุด", quantity: 7, unitPrice: 150, notes: "ห้องนอน + ห้องน้ำ + หลังบ้าน" },
      { category: "หมวดงานวงกบ ประตู หน้าต่าง (Door & Window Work)", seq: 11, name: "บานพับสแตนเลส 4\"", unit: "ตัว", quantity: 24, unitPrice: 35, notes: "บานละ 3 ตัว" },
      { category: "หมวดงานวงกบ ประตู หน้าต่าง (Door & Window Work)", seq: 12, name: "กลอนประตูห้องน้ำ/หลังบ้าน Hafele SS304", unit: "ชุด", quantity: 3, unitPrice: 150, notes: "กลอนล๊อคในตัว" },
      { category: "หมวดงานวงกบ ประตู หน้าต่าง (Door & Window Work)", seq: 13, name: "ซีลยางกันกระแทกประตู", unit: "ม้วน", quantity: 1, unitPrice: 250, notes: "ใช้รอบวงกบ" },
      { category: "หมวดงานวงกบ ประตู หน้าต่าง (Door & Window Work)", seq: 14, name: "คิ้วอลูมิเนียมรอบวงกบ", unit: "เมตร", quantity: 10, unitPrice: 70, notes: null },
      { category: "หมวดงานวงกบ ประตู หน้าต่าง (Door & Window Work)", seq: 15, name: "ค่าแรงติดตั้งวงกบ–บานประตู–หน้าต่าง", unit: "บาน", quantity: 9, unitPrice: 500, notes: "รวมประตู–หน้าต่างทั้งหมด" },
      { category: "หมวดงานฝ้าเพดาน (Ceiling Work)", seq: 1, name: "แผ่นฝ้ายิปซั่มตราช้าง หนา 9 มม. (ฉาบเรียบ)", unit: "แผ่น (1.2x2.4 ม.)", quantity: 35, unitPrice: 195, notes: "ใช้ฝ้าภายในทั้งหมด" },
      { category: "หมวดงานฝ้าเพดาน (Ceiling Work)", seq: 2, name: "แผ่นฝ้ายิปซั่มกันชื้นตราช้าง หนา 9 มม.", unit: "แผ่น (1.2x2.4 ม.)", quantity: 12, unitPrice: 285, notes: "ใช้ห้องน้ำ 2 ห้อง" },
      { category: "หมวดงานฝ้าเพดาน (Ceiling Work)", seq: 3, name: "โครงคร่าวฝ้า (Main Tee + Cross Tee + Wall Angle)", unit: "ตร.ม.", quantity: 60, unitPrice: 110, notes: "ใช้สำหรับยึดแผ่นฝ้า" },
      { category: "หมวดงานฝ้าเพดาน (Ceiling Work)", seq: 4, name: "สกรูยึดฝ้า / ดิวเวล / สกรูปลายสว่าน", unit: "กล่อง", quantity: 2, unitPrice: 350, notes: "อุปกรณ์ติดตั้ง" },
      { category: "หมวดงานฝ้าเพดาน (Ceiling Work)", seq: 5, name: "ปูนฉาบรอยต่อฝ้า (ตราช้าง) + เทปใยแก้ว", unit: "ชุด", quantity: 3, unitPrice: 380, notes: "ปิดรอยต่อรอยหัวสกรู" },
      { category: "หมวดงานฝ้าเพดาน (Ceiling Work)", seq: 6, name: "สีทาฝ้า TOA Ceiling White (1 แกลลอน 5 ลิตร)", unit: "แกลลอน", quantity: 2, unitPrice: 950, notes: "ทาฝ้าภายใน" },
      { category: "หมวดงานฝ้าเพดาน (Ceiling Work)", seq: 7, name: "สีรองพื้นปูนเก่า TOA 101 ขาวควันบุหรี่", unit: "แกลลอน", quantity: 1, unitPrice: 890, notes: "ทารองพื้นฝ้า" },
      { category: "หมวดงานฝ้าเพดาน (Ceiling Work)", seq: 8, name: "ฝ้าหลุมซ่อนไฟ (ฝ้าฉาบเรียบ 1 ชั้น ซ่อนโคม)", unit: "ตร.ม.", quantity: 12, unitPrice: 350, notes: "บริเวณห้องรับแขก" },
      { category: "หมวดงานฝ้าเพดาน (Ceiling Work)", seq: 9, name: "โคมดาวน์ไลท์ LED กลม (Philips 8W สีเหลืองอ่อนอบอุ่น)", unit: "ดวง", quantity: 15, unitPrice: 250, notes: "ใช้ในฝ้าหลุมและโถงกลาง" },
      { category: "หมวดงานฝ้าเพดาน (Ceiling Work)", seq: 10, name: "โครงเหล็กกล่อง 1\"x1\" หนา 1.2 มม.", unit: "เส้น (6 ม.)", quantity: 10, unitPrice: 200, notes: "ใช้ทำโครงฝ้าหลุม" },
      { category: "หมวดงานฝ้าเพดาน (Ceiling Work)", seq: 11, name: "ค่าแรงติดตั้งฝ้าเพดาน", unit: "ตร.ม.", quantity: 72, unitPrice: 200, notes: "รวมห้องน้ำและห้องหลักทั้งหมด" },
      { category: "หมวดงานฝ้าเพดาน (Ceiling Work)", seq: 12, name: "ค่าแรงทำฝ้าหลุมและติดโคมไฟ", unit: "ตร.ม.", quantity: 12, unitPrice: 250, notes: "รวมแรงไฟฟ้าเบื้องต้น" },
      { category: "หมวดงานตกแต่งพื้น–ผนัง (Floor & Wall Decoration)", seq: 1, name: "กระเบื้องปูพื้น COTTO 60x60 ซม. (แกรนิตโต้)", unit: "ตร.ม.", quantity: 46, unitPrice: 250, notes: "ห้องนอน + ห้องโถง" },
      { category: "หมวดงานตกแต่งพื้น–ผนัง (Floor & Wall Decoration)", seq: 2, name: "กระเบื้องปูพื้นห้องน้ำ COTTO 40x40 ซม.", unit: "ตร.ม.", quantity: 10, unitPrice: 250, notes: "2 ห้องน้ำ" },
      { category: "หมวดงานตกแต่งพื้น–ผนัง (Floor & Wall Decoration)", seq: 3, name: "กระเบื้องผนังห้องน้ำ COTTO 25x45 ซม.", unit: "ตร.ม.", quantity: 56, unitPrice: 250, notes: "สูง 2.8 ม." },
      { category: "หมวดงานตกแต่งพื้น–ผนัง (Floor & Wall Decoration)", seq: 4, name: "ปูนกาวปูกระเบื้อง Smart Fix", unit: "ถุง (20 กก.)", quantity: 10, unitPrice: 180, notes: "สำหรับพื้นและผนัง" },
      { category: "หมวดงานตกแต่งพื้น–ผนัง (Floor & Wall Decoration)", seq: 5, name: "ปูนเขียว SCG สำหรับปูกระเบื้องพื้น", unit: "ถุง (50 กก.)", quantity: 15, unitPrice: 120, notes: "ใช้พื้นทั้งหมด" },
      { category: "หมวดงานตกแต่งพื้น–ผนัง (Floor & Wall Decoration)", seq: 6, name: "ปูนยาแนว สีเทาอ่อน", unit: "ถุง (1 กก.)", quantity: 8, unitPrice: 55, notes: null },
      { category: "หมวดงานตกแต่งพื้น–ผนัง (Floor & Wall Decoration)", seq: 7, name: "คิ้วอลูมิเนียมขอบกระเบื้อง 1/2 นิ้ว", unit: "เส้น (2.4 ม.)", quantity: 10, unitPrice: 100, notes: "ห้องน้ำ+ครัว" },
      { category: "หมวดงานตกแต่งพื้น–ผนัง (Floor & Wall Decoration)", seq: 8, name: "จมูกบันได PVC (สีเทา)", unit: "เส้น (2.4 ม.)", quantity: 4, unitPrice: 120, notes: null },
      { category: "หมวดงานตกแต่งพื้น–ผนัง (Floor & Wall Decoration)", seq: 9, name: "ค่าแรงปูกระเบื้องพื้นและผนัง", unit: "ตร.ม.", quantity: 122, unitPrice: 220, notes: "รวมพื้น+ผนังทั้งหมด" },
      { category: "หมวดตกแต่งทั่วไป (General Decoration Work)", seq: 1, name: "บัวพื้นไม้เทียม (SCG Smart Wood) หนา 10 มม. สีไม้มินิมอล", unit: "เมตร", quantity: 48, unitPrice: 140, notes: "รอบห้องภายในบ้าน" },
      { category: "หมวดตกแต่งทั่วไป (General Decoration Work)", seq: 2, name: "บัวปูนขอบหน้าต่าง / ประตู", unit: "เมตร", quantity: 32, unitPrice: 120, notes: "รวมหน้าต่างทุกบาน" },
      { category: "หมวดตกแต่งทั่วไป (General Decoration Work)", seq: 3, name: "ปูนฉาบตกแต่งผิวเรียบ TOA 1100", unit: "ถุง (20 กก.)", quantity: 15, unitPrice: 180, notes: "ใช้สำหรับเก็บผิวผนัง" },
      { category: "หมวดตกแต่งทั่วไป (General Decoration Work)", seq: 4, name: "ระแนงเมทัลชีทลอนเล็ก (สีไม้มินิมอลอ่อน)", unit: "ตร.ม.", quantity: 20, unitPrice: 300, notes: "ตกแต่งหน้าและข้างบ้าน" },
      { category: "หมวดตกแต่งทั่วไป (General Decoration Work)", seq: 5, name: "โครงเหล็กรับระแนง (เหล็กกล่อง 1\"x1\" หนา 1.2 มม.)", unit: "เส้น (6 ม.)", quantity: 12, unitPrice: 280, notes: "สำหรับติดตั้งระแนง" },
      { category: "หมวดตกแต่งทั่วไป (General Decoration Work)", seq: 6, name: "น็อตยิงแผ่น + สกรูเกลียวปล่อย", unit: "กล่อง", quantity: 1, unitPrice: 380, notes: null },
      { category: "หมวดตกแต่งทั่วไป (General Decoration Work)", seq: 7, name: "ซิลิโคนยาแนว / อุปกรณ์เก็บงานระแนง", unit: "หลอด", quantity: 5, unitPrice: 100, notes: null },
      { category: "หมวดตกแต่งทั่วไป (General Decoration Work)", seq: 8, name: "ค่าแรงติดตั้งบัวพื้นและบัวปูนตกแต่ง", unit: "ตร.ม.", quantity: 80, unitPrice: 80, notes: "รวมงานเก็บสี" },
      { category: "หมวดตกแต่งทั่วไป (General Decoration Work)", seq: 9, name: "ค่าแรงติดตั้งระแนงเหล็กและเมทัลชีทตกแต่ง", unit: "ตร.ม.", quantity: 20, unitPrice: 80, notes: "รวมโครงเหล็กและยิงแผ่น" },
      { category: "หมวดไฟฟ้าและแสงสว่าง (Electrical System Work)", seq: 1, name: "สายไฟ YAZAKI 2x2.5 sq.mm (VAF)", unit: "ม้วน (100 ม.)", quantity: 3, unitPrice: 2150, notes: "วงจรปลั๊ก" },
      { category: "หมวดไฟฟ้าและแสงสว่าง (Electrical System Work)", seq: 2, name: "สายไฟ YAZAKI 2x1.5 sq.mm (VAF)", unit: "ม้วน (100 ม.)", quantity: 2, unitPrice: 1750, notes: "วงจรไฟส่องสว่าง" },
      { category: "หมวดไฟฟ้าและแสงสว่าง (Electrical System Work)", seq: 3, name: "สายไฟ YAZAKI 3x6 sq.mm (VAF-G)", unit: "ม้วน (100 ม.)", quantity: 1, unitPrice: 3600, notes: "สายเมนเข้าบ้าน" },
      { category: "หมวดไฟฟ้าและแสงสว่าง (Electrical System Work)", seq: 4, name: "ท่อร้อยสายไฟ PVC สีขาว ขนาด 20 มม.", unit: "เส้น (4 ม.)", quantity: 40, unitPrice: 40, notes: "สำหรับงานฝังผนัง" },
      { category: "หมวดไฟฟ้าและแสงสว่าง (Electrical System Work)", seq: 5, name: "ข้อต่อ /ข้องอ / แคลมป์ยึดท่อ", unit: "ชุด", quantity: 1, unitPrice: 850, notes: "รวมอุปกรณ์ย่อย" },
      { category: "หมวดไฟฟ้าและแสงสว่าง (Electrical System Work)", seq: 6, name: "ตู้โหลดเซ็นเตอร์ Panasonic 12 ช่อง", unit: "ชุด", quantity: 1, unitPrice: 2800, notes: "รวมเบรกเกอร์ย่อย" },
      { category: "หมวดไฟฟ้าและแสงสว่าง (Electrical System Work)", seq: 7, name: "เบรกเกอร์หลัก Panasonic 32A 2P", unit: "ตัว", quantity: 1, unitPrice: 890, notes: "ตัดไฟหลัก" },
      { category: "หมวดไฟฟ้าและแสงสว่าง (Electrical System Work)", seq: 8, name: "สวิตช์ไฟ Panasonic Full Color Series", unit: "ตัว", quantity: 20, unitPrice: 95, notes: "เดี่ยว / คู่" },
      { category: "หมวดไฟฟ้าและแสงสว่าง (Electrical System Work)", seq: 9, name: "ปลั๊กไฟ Panasonic Full Color Series", unit: "ตัว", quantity: 15, unitPrice: 125, notes: "ปลั๊กคู่" },
      { category: "หมวดไฟฟ้าและแสงสว่าง (Electrical System Work)", seq: 10, name: "ดาวน์ไลต์ LED ฝังฝ้า 6\" (Dawnlife Warm White 12W)", unit: "ดวง", quantity: 18, unitPrice: 220, notes: "ห้องโถง / ห้องนอน" },
      { category: "หมวดไฟฟ้าและแสงสว่าง (Electrical System Work)", seq: 11, name: "โคมไฟกันชื้นห้องน้ำ (Philips 12W)", unit: "ดวง", quantity: 2, unitPrice: 320, notes: null },
      { category: "หมวดไฟฟ้าและแสงสว่าง (Electrical System Work)", seq: 12, name: "โคมไฟกิ่งภายนอก (ไฟกิ่งสีดำอบทราย 12W)", unit: "ดวง", quantity: 3, unitPrice: 450, notes: "หน้าบ้าน–หลังบ้าน" },
      { category: "หมวดไฟฟ้าและแสงสว่าง (Electrical System Work)", seq: 13, name: "สายดิน YAZAKI 6 sq.mm + แท่งกราวด์ทองแดง 5 ฟุต", unit: "ชุด", quantity: 1, unitPrice: 950, notes: "ระบบกราวด์ครบชุด" },
      { category: "หมวดไฟฟ้าและแสงสว่าง (Electrical System Work)", seq: 14, name: "ท่อ HDPE ร้อยสายไฟ 40 มม. ยาว 100 เมตร ตรามือ รุ่น 398-40-1R(PN6) สีดำ", unit: "ม้วน (100 ม.)", quantity: 1, unitPrice: 1970, notes: "สำหรับเดินสายไฟลงดิน" },
      { category: "หมวดไฟฟ้าและแสงสว่าง (Electrical System Work)", seq: 15, name: "อุปกรณ์ย่อย (เทปพันสาย, เดินตะปู, กล่องปลั๊ก)", unit: "ชุด", quantity: 1, unitPrice: 1200, notes: "รวมทั้งหมด" },
      { category: "หมวดไฟฟ้าและแสงสว่าง (Electrical System Work)", seq: 16, name: "ค่าแรงติดตั้งระบบไฟฟ้าภายใน–ภายนอก", unit: "งานเหมาจ่าย", quantity: 1, unitPrice: 8000, notes: "รวมร้อยสาย+ติดตั้งโคม" },
      { category: "หมวดสุขาภิบาล (Sanitary & Plumbing System)", seq: 1, name: "ท่อน้ำดี PVC SCG สีฟ้า ชั้น 8.5 ขนาด 1/2\"–3/4\"", unit: "เส้น (4 ม.)", quantity: 40, unitPrice: 58, notes: "เดินน้ำดีทั่วบ้าน" },
      { category: "หมวดสุขาภิบาล (Sanitary & Plumbing System)", seq: 2, name: "ข้อต่อ PVC / ยูเนี่ยน / ข้องอ / สามทาง", unit: "ชุด", quantity: 1, unitPrice: 1000, notes: "รวมอุปกรณ์ประกอบ" },
      { category: "หมวดสุขาภิบาล (Sanitary & Plumbing System)", seq: 3, name: "บอลวาล์วทองเหลือง SCG 1/2\"", unit: "ตัว", quantity: 6, unitPrice: 150, notes: "จุดแยกน้ำ" },
      { category: "หมวดสุขาภิบาล (Sanitary & Plumbing System)", seq: 4, name: "ท่อน้ำทิ้ง PVC สีเทา SCG ชั้น 8.5 ขนาด 2\"–4\"", unit: "เส้น (4 ม.)", quantity: 30, unitPrice: 95, notes: "รวมแนวท่อหลัก" },
      { category: "หมวดสุขาภิบาล (Sanitary & Plumbing System)", seq: 5, name: "ข้อต่อ / ข้องอ / แหวนยางท่อระบายน้ำ", unit: "ชุด", quantity: 1, unitPrice: 900, notes: "รวมอุปกรณ์ประกอบ" },
      { category: "หมวดสุขาภิบาล (Sanitary & Plumbing System)", seq: 6, name: "ท่อน้ำทิ้งอ่างล้างหน้า", unit: "ชุด", quantity: 2, unitPrice: 220, notes: null },
      { category: "หมวดสุขาภิบาล (Sanitary & Plumbing System)", seq: 7, name: "ถังแซท 1 ถัง ขนาด 1,000 ลิตร (DOS Nature Bio)", unit: "ใบ", quantity: 1, unitPrice: 4500, notes: "สำหรับ 2 ห้องน้ำ" },
      { category: "หมวดสุขาภิบาล (Sanitary & Plumbing System)", seq: 8, name: "บ่อพักคอนกรีตเสริมเหล็ก (40x40x60 ซม.)", unit: "บ่อ", quantity: 4, unitPrice: 950, notes: "รอบตัวบ้าน" },
      { category: "หมวดสุขาภิบาล (Sanitary & Plumbing System)", seq: 9, name: "สุขภัณฑ์ COTTO แบบประหยัดน้ำ (รุ่น C11247)", unit: "ชุด", quantity: 2, unitPrice: 3400, notes: "โถนั่งชักโครก" },
      { category: "หมวดสุขาภิบาล (Sanitary & Plumbing System)", seq: 10, name: "อ่างล้างหน้า COTTO รุ่น C004", unit: "ชุด", quantity: 2, unitPrice: 1150, notes: "พร้อมขาและอุปกรณ์" },
      { category: "หมวดสุขาภิบาล (Sanitary & Plumbing System)", seq: 11, name: "ก๊อกน้ำ COTTO รุ่น CT170C", unit: "ตัว", quantity: 5, unitPrice: 450, notes: "รวมอ่างและฝักบัว" },
      { category: "หมวดสุขาภิบาล (Sanitary & Plumbing System)", seq: 12, name: "ฝักบัวพร้อมสายอ่อน COTTO รุ่น ZB-120", unit: "ชุด", quantity: 2, unitPrice: 650, notes: null },
      { category: "หมวดสุขาภิบาล (Sanitary & Plumbing System)", seq: 13, name: "สายชำระ COTTO รุ่น ZT-100", unit: "ชุด", quantity: 2, unitPrice: 380, notes: null },
      { category: "หมวดสุขาภิบาล (Sanitary & Plumbing System)", seq: 14, name: "ปูนประสานท่อ, เทปพันเกลียว, อุปกรณ์ย่อย", unit: "ชุด", quantity: 1, unitPrice: 600, notes: "รวมทั้งหมด" },
      { category: "หมวดสุขาภิบาล (Sanitary & Plumbing System)", seq: 15, name: "ค่าแรงติดตั้งระบบท่อน้ำดี–น้ำทิ้ง / สุขภัณฑ์", unit: "งานเหมาจ่าย", quantity: 1, unitPrice: 8000, notes: "รวมฝังท่อและติดตั้งครบ" },
      { category: "หมวดสีและงานทาสี (Painting & Coating Work)", seq: 1, name: "สีรองพื้นปูนใหม่ TOA 105 Smooth Sealer", unit: "แกลลอน (3.5 ลิตร)", quantity: 8, unitPrice: 790, notes: "สำหรับภายนอก–ภายใน" },
      { category: "หมวดสีและงานทาสี (Painting & Coating Work)", seq: 2, name: "สีทาภายนอก TOA 4 Seasons Semi-Gloss", unit: "แกลลอน (3.5 ลิตร)", quantity: 10, unitPrice: 1050, notes: "ผนังภายนอกทั้งหมด" },
      { category: "หมวดสีและงานทาสี (Painting & Coating Work)", seq: 3, name: "สีทาภายใน TOA SuperShield Duraclean A+", unit: "แกลลอน (3.5 ลิตร)", quantity: 8, unitPrice: 1180, notes: "ห้องโถง / ห้องนอน" },
      { category: "หมวดสีและงานทาสี (Painting & Coating Work)", seq: 4, name: "สีทาฝ้าเพดาน TOA Ceiling Paint", unit: "แกลลอน (3.5 ลิตร)", quantity: 4, unitPrice: 690, notes: "สีขาวด้าน" },
      { category: "หมวดสีและงานทาสี (Painting & Coating Work)", seq: 5, name: "เทปปิดรอยต่อ TOA Fiber Mesh", unit: "ม้วน", quantity: 1, unitPrice: 450, notes: "รอยต่อผนัง–ฝ้า" },
      { category: "หมวดสีและงานทาสี (Painting & Coating Work)", seq: 6, name: "อุปกรณ์สิ้นเปลือง (ลูกกลิ้ง, เทปกาว, กระดาษทราย ฯลฯ)", unit: "ชุด", quantity: 1, unitPrice: 1200, notes: "รวมทั้งหมด" },
      { category: "หมวดสีและงานทาสี (Painting & Coating Work)", seq: 7, name: "ค่าแรงทาสีภายนอก–ภายใน ", unit: "ตร.ม.", quantity: 260, unitPrice: 60, notes: "รวมฝ้าและกันซึม" },
      { category: "หมวดงานเบ็ดเตล็ด (Miscellaneous Work)", seq: 1, name: "ทรายหยาบผสมปูน (รถหกล้อ)", unit: "คัน", quantity: 4, unitPrice: 2000, notes: null },
      { category: "หมวดงานเบ็ดเตล็ด (Miscellaneous Work)", seq: 2, name: "ทรายละเอียดผสมปูน (รถหกล้อ)", unit: "คัน", quantity: 2, unitPrice: 2200, notes: null },
      { category: "หมวดงานเบ็ดเตล็ด (Miscellaneous Work)", seq: 3, name: "ทรายถมปรับพื้นที่รอบบ้าน (รถหกล้อ)", unit: "คัน", quantity: 4, unitPrice: 1800, notes: null },
      { category: "หมวดงานเบ็ดเตล็ด (Miscellaneous Work)", seq: 4, name: "หินเบอร์ 3 ผสมปูน (รถหกล้อ)", unit: "คัน", quantity: 2, unitPrice: 2500, notes: null },
      { category: "หมวดงานเบ็ดเตล็ด (Miscellaneous Work)", seq: 5, name: "ปูนซีเมนต์ผสมทั่วไป (อินทรีเขียว SCG 240 Ksc)", unit: "ถุง", quantity: 60, unitPrice: 135, notes: null },
      { category: "หมวดงานเบ็ดเตล็ด (Miscellaneous Work)", seq: 6, name: "ไม้แบบ (ใช้สำหรับเทพื้น/ขอบรอบบ้าน)", unit: "ตร.ม.", quantity: 40, unitPrice: 60, notes: null },
      { category: "หมวดงานเบ็ดเตล็ด (Miscellaneous Work)", seq: 7, name: "ลวดผูกเหล็ก", unit: "มัด", quantity: 5, unitPrice: 70, notes: null },
      { category: "หมวดงานเบ็ดเตล็ด (Miscellaneous Work)", seq: 8, name: "ตะปูขนาด 2\", 3\"", unit: "กล่อง", quantity: 1, unitPrice: 680, notes: null },
      { category: "หมวดงานเบ็ดเตล็ด (Miscellaneous Work)", seq: 9, name: "ใบตัดเหล็ก / ใบเจียร / กระดาษทราย (วัสดุสิ้นเปลือง)", unit: "ชุด", quantity: 1, unitPrice: 1000, notes: null },
      { category: "หมวดงานเบ็ดเตล็ด (Miscellaneous Work)", seq: 10, name: "ค่าแรงเครื่องจักรกลหนัก (รถแม็คโครปรับพื้นที่ / เทพื้นรอบบ้าน)", unit: "วัน", quantity: 2, unitPrice: 4000, notes: null },
      { category: "หมวดงานเบ็ดเตล็ด (Miscellaneous Work)", seq: 11, name: "เทพื้นคอนกรีตรอบตัวบ้าน หนา 10 ซม. (รวมค่าแรงและวัสดุ)", unit: "ตร.ม.", quantity: 32, unitPrice: 100, notes: null },
    ],
  },
];
